
spring:
  datasource:
    url: jdbc:mysql://localhost:3304/customer_db
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

#hibernate.ddl-auto: create
#hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
hibernate.hbm2ddl.auto: update

#spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect